### ISSUE TITLE
Android minSdk version too high

### ISSUE THREAD

**Issue by Skaldebane** [Kamel-Media/Kamel#115]
Hi, I just updated the library to 1.0.0-beta.7 (from 1.0.0-beta.4), and now I'm getting this error while building the Android target:

```
.../composeApp/src/androidMain/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 24 cannot be smaller than version 28 declared in library [media.kamel:kamel-decoder-animated-image-android:1.0.0-beta.7] ~/.gradle/caches/transforms-4/...../transformed/kamel-decoder-animated-image-release/AndroidManifest.xml as the library might be using APIs not available in 24
	Suggestion: use a compatible library with a minSdk of at most 24,
		or increase this project's minSdk version to at least 28,
		or use tools:overrideLibrary="io.kamel.image" to force usage (may lead to runtime failures)
```

I understand that the minSdk for Kamel (in particular the `kamel-decoder-animated-image-android` artifact) has been bumped to 28 for some reason, but it feels a bit restrictive. It's the only library thus far that doesn't support all the way down to SDK 21 (and at the very least, the default for new multiplatform projects, SDK 24).

Note that I'm using the `media.kamel:kamel-image-default` artifact, and this is pulled in automatically with it. If this particular artifact requires use of SDK 28, maybe it's a good idea to remove it from the `kamel-image-default` dependency.

Another approach is building some backwards-compatible backport of this functionality for older Android versions, but I'm not sure how doable is that (I don't use the functionality of this dependency myself, so I don't know much), or maybe setting minSdk to 21 and annotating the relevant functions with `@TargetApi` to show warnings in the IDE.

Just throwing some ideas, would love to know what you think about this.

And thanks for the great library!

**Comment by luca992** [comment]
Hmm yeah good point. I think I'll try lowering the minsdk and adding `@TargetApi` annotations. Having gif support in the defaults is something people might want (up for debate). I'm sure an implementation could be made for lower versions, but I do not have time at the moment unfortunately.

**Comment by Skaldebane** [comment]
Thanks for the response! Yeah, that seems like a good approach for a start.

As for implementing it for all API versions, Coil seems to have implemented a backwards-compatible (but slower) decoder, as the note at the bottom of this page indicates: https://coil-kt.github.io/coil/gifs/. Maybe you could take inspiration from them (if I find some time, I may give it a try and submit a PR if I have any success with it).

In Coil they simply expose both decoders, and it's up to the developer to choose which one to use (usually, the developer should check the SDK version, if larger than 28 use the optimized one, otherwise the compat one), with code like this in a custom `Application` subclass:

```kotlin
class MyApp : Application(), ImageLoaderFactory {
    override fun newImageLoader(): ImageLoader {
        return ImageLoader(this)
            .newBuilder()
            .components(
                // native decoder (fast)
                if (Build.VERSION.SDK_INT >= 28)  add(ImageDecoderDecoder.Factory())
                // backwards compatible decoder (slow)
                else add(GifDecoder.Factory())
            )
            .build()
    }
}
```

Now that's Coil, so this might have to be done differently in Kamel. The main thing in question is whether such a check should happen automatically, or whether it's the library consumer's responsibility to do this.

My personal preference would be for this to implicitly be done for me (and have the library choose the most efficient path based on the SDK version), but there may be some benefits to making this explicit that I'm missing.

**Comment by luca992** [comment]
I could always make two android decoders. And have the android version depend on both and pick according to api version. So both would be included in `kamel-image-default`. But if a person didn't want to include both. They can always choose which dependencies they want... and/or I could just make different versions of `kamel-image-default` like `kamel-image-default-android-28'

**Comment by Daanfb** [comment]
With the 1.0.1 version i have the same problem. Did you find any solution?
 @luca992 @Skaldebane

**Comment by Skaldebane** [comment]
I don't think there's anything for the moment. I may look into it later today if I find some time, and (hopefully) submit a PR!

**Comment by Skaldebane** [comment]
Any updates on this?

**Comment by luca992** [comment]
@sureshmaidaragi1919 

Try `1.0.4-SNAPSHOT`. I lowered the minSdk to 23 and have throw a runtime error if attempting to use on less than android 28.

**Comment by sureshmaidaragi1919** [comment]
@luca992 it saying not found

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':androidApp:mergeDevDebugNativeLibs'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.gradle.api.internal.artifacts.ivyservice.TypedResolveException: Could not resolve all files for configuration ':androidApp:devDebugRuntimeClasspath'.
	at org.gradle.api.internal.artifacts.ResolveExceptionMapper.mapFailure(ResolveExceptionMapper.java:68)
	at org.gradle.api.internal.artifacts.ResolveExceptionMapper.mapFailures(ResolveExceptionMapper.java:60)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$DefaultResolutionHost.mapFailure(DefaultConfiguration.java:1988)
	at org.gradle.api.internal.artifacts.configurations.ResolutionHost.rethrowFailure(ResolutionHost.java:48)
	at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.maybeThrowResolutionFailures(ResolutionBackedFileCollection.java:84)
	at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.visitContents(ResolutionBackedFileCollection.java:74)
	at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:123)
	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:164)
	at org.gradle.api.internal.file.FilteredFileCollection.iterator(FilteredFileCollection.java:80)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:264)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$2.visitCollection(DefaultConfigurableFileCollection.java:394)
	at org.gradle.api.internal.file.AbstractFileCollection.visitContents(AbstractFileCollection.java:365)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:360)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.lambda$calculateFinalizedValue$1(DefaultConfigurableFileCollection.java:391)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:67)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.visitContents(DefaultConfigurableFileCollection.java:594)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.calculateFinalizedValue(DefaultConfigurableFileCollection.java:391)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.finalizeNow(DefaultConfigurableFileCollection.java:120)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.lambda$visitChildren$2(DefaultConfigurableFileCollection.java:415)
	at org.gradle.api.internal.provider.ValueState.finalizeOnReadIfNeeded(ValueState.java:139)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitChildren(DefaultConfigurableFileCollection.java:415)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:113)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:360)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:113)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:67)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:92)
	at org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection.visitChildren(DefaultFileCollectionFactory.java:306)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:113)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:360)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:113)
	at org.gradle.api.internal.tasks.PropertyFileCollection.visitChildren(PropertyFileCollection.java:48)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:113)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:360)
	at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:47)
	at org.gradle.internal.execution.impl.DefaultInputFingerprinter$InputCollectingVisitor.visitInputFileProperty(DefaultInputFingerprinter.java:133)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep$1.visitInputFileProperty(AbstractSkipEmptyWorkStep.java:104)
	at org.gradle.api.internal.tasks.execution.TaskExecution.visitRegularInputs(TaskExecution.java:324)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.lambda$fingerprintPrimaryInputs$2(AbstractSkipEmptyWorkStep.java:100)
	at org.gradle.internal.execution.impl.DefaultInputFingerprinter.fingerprintInputProperties(DefaultInputFingerprinter.java:63)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.fingerprintPrimaryInputs(AbstractSkipEmptyWorkStep.java:95)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:52)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:75)
	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:41)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$execute$0(AssignMutableWorkspaceStep.java:35)
	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:289)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:31)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:22)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:48)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:35)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:61)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:127)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find media.kamel:kamel-decoder-animated-image:1.0.4-SNAPSHOT.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/media/kamel/kamel-decoder-animated-image/1.0.4-SNAPSHOT/maven-metadata.xml
  - https://dl.google.com/dl/android/maven2/media/kamel/kamel-decoder-animated-image/1.0.4-SNAPSHOT/kamel-decoder-animated-image-1.0.4-SNAPSHOT.pom
  - https://repo.maven.apache.org/maven2/media/kamel/kamel-decoder-animated-image/1.0.4-SNAPSHOT/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/media/kamel/kamel-decoder-animated-image/1.0.4-SNAPSHOT/kamel-decoder-animated-image-1.0.4-SNAPSHOT.pom
  - https://maven.pkg.jetbrains.space/public/p/compose/dev/media/kamel/kamel-decoder-animated-image/1.0.4-SNAPSHOT/maven-metadata.xml
  - https://maven.pkg.jetbrains.space/public/p/compose/dev/media/kamel/kamel-decoder-animated-image/1.0.4-SNAPSHOT/kamel-decoder-animated-image-1.0.4-SNAPSHOT.pom
  - https://nexus3.penpencil.co/repository/maven-hosted-snapshots/media/kamel/kamel-decoder-animated-image/1.0.4-SNAPSHOT/maven-metadata.xml
  - https://nexus3.penpencil.co/repository/maven-hosted-snapshots/media/kamel/kamel-decoder-animated-image/1.0.4-SNAPSHOT/kamel-decoder-animated-image-1.0.4-SNAPSHOT.pom
  - https://jitpack.io/media/kamel/kamel-decoder-animated-image/1.0.4-SNAPSHOT/maven-metadata.xml
  - https://jitpack.io/media/kamel/kamel-decoder-animated-image/1.0.4-SNAPSHOT/kamel-decoder-animated-image-1.0.4-SNAPSHOT.pom
Required by:
    project :androidApp > project :pitaraShared > project :kmm-pw-ui-module
```

**Comment by luca992** [comment]
@sureshmaidaragi1919 add this repo to try it

```
repositories {
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
}
```

**Comment by sureshmaidaragi1919** [comment]
it showing to update `compileSdk = 35` currently we used `compileSdk=34` possible for you todo the same?

**Comment by luca992** [comment]
I don't think that matters for libraries. But sure I'll update it

**Comment by luca992** [comment]
`1.0.4.1-SNAPSHOT` is being [published](https://github.com/Kamel-Media/Kamel/actions/runs/14350074866). switched to compileSdk = 36

**Comment by sureshmaidaragi1919** [comment]
ho no please lower down the compileSdk too  I mean compile sdk <35

**Comment by sureshmaidaragi1919** [comment]
@luca992 can you please make the above changes?

**Comment by luca992** [comment]
@sureshmaidaragi1919 I'm not lowering it. I have set `minSdk = 21` already. You are likely doing something wrong.

**Comment by sureshmaidaragi1919** [comment]
@luca992 I mean to set the compileSdk to **34** instead **36**

**Comment by luca992** [comment]
I should not have to lower `compileSdk` for you to use kamel in an app using `compileSdk = 34`.

https://stackoverflow.com/questions/24510219/what-is-the-difference-between-min-sdk-version-target-sdk-version-and-comp

It is not the responsibility of a library to lower the compileSdk.

If you are not ready to support the latest `compileSdk` android api level in your app there is a `android.defaultConfig.targetSdk` option which should let you use the latest compileSdk while targeting a lower version which in your case `targetSdk = 34`.


I changed the sample to use `compileSdk = 34` and got these errors which I am guessing you are seeing:

```
5 issues were found when checking AAR metadata:

  1.  Dependency 'androidx.activity:activity-ktx:1.10.1' requires libraries and applications that
      depend on it to compile against version 35 or later of the
      Android APIs.

      :kamel-samples is currently compiled against android-34.

      Recommended action: Update this project to use a newer compileSdk
      of at least 35, for example 35.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).

  2.  Dependency 'androidx.activity:activity:1.10.1' requires libraries and applications that
      depend on it to compile against version 35 or later of the
      Android APIs.

      :kamel-samples is currently compiled against android-34.

      Recommended action: Update this project to use a newer compileSdk
      of at least 35, for example 35.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).

  3.  Dependency 'androidx.activity:activity-compose:1.10.1' requires libraries and applications that
      depend on it to compile against version 35 or later of the
      Android APIs.

      :kamel-samples is currently compiled against android-34.

      Recommended action: Update this project to use a newer compileSdk
      of at least 35, for example 35.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).

  4.  Dependency 'androidx.core:core-ktx:1.15.0' requires libraries and applications that
      depend on it to compile against version 35 or later of the
      Android APIs.

      :kamel-samples is currently compiled against android-34.

      Recommended action: Update this project to use a newer compileSdk
      of at least 35, for example 35.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).

  5.  Dependency 'androidx.core:core:1.15.0' requires libraries and applications that
      depend on it to compile against version 35 or later of the
      Android APIs.

      :kamel-samples is currently compiled against android-34.

      Recommended action: Update this project to use a newer compileSdk
      of at least 35, for example 35.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).
```

setting `targetSdk = 34` allows it to build with the latest `compileSdk`.
 
Or you can downgrade your androidx dependencies to a version which supports your compileSdk, or update your compileSdk as they tell you. Setting the tarket is probably your best option.

**Comment by sureshmaidaragi1919** [comment]
@luca992 any updates on [above](https://github.com/Kamel-Media/Kamel/issues/115#issuecomment-2812644131)?

**Comment by luca992** [comment]
should be there https://s01.oss.sonatype.org/content/repositories/snapshots/media/kamel/kamel-decoder-animated-image-iossimulatorarm64/

**Comment by sureshmaidaragi1919** [comment]
I have tried cleaning the update build cache still no luck, is there anything needs to do for ios?

**Comment by luca992** [comment]
<img width="700" alt="Image" src="https://github.com/user-attachments/assets/339524c1-73e7-4557-8045-b20778c2d971" />

If you you the snapshot repo set properly. I have no idea. It works perfectly fine for me when I use it in the sample. You can try `1.0.4.2-SNAPSHOT` I just put up, but both work

**Comment by myuksektepe** [comment]
**libs.versions.toml**

```
[versions]
kamel = "1.0.4.2-SNAPSHOT"

[libraries]
kamel-image-default = { module = "media.kamel:kamel-image-default", version.ref = "kamel" }
```



**settings.gradle.kts**

```
pluginManagement {
    repositories {
        // ...
        maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
    }
}

dependencyResolutionManagement {
    repositories {
        // ...
        maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
    }
}
```


**build.gradle.kts**

```
sourceSets {
    commonMain.dependencies {
        // ...

        // Kamel (Image)
        implementation(libs.kamel.image.default)
    }
}
```


**Screen.kt**

```
                val painterResource = asyncPainterResource("URL")
                KamelImage(
                    modifier = Modifier
                        .clip(AppTheme.shapes.large)
                        .size(200.dp),
                    contentScale = ContentScale.Crop,
                    resource = { painterResource },
                    contentDescription = null,
                    onFailure = { error ->
                        Napier.e("Error while loading image ${error.message}")
                    }
                )
```

that is working for **compileSdk = 35** and **minSdk = 21** 👍

**Comment by Skaldebane** [comment]
@luca992 Seems like you forgot to set 1.0.5 as the "Latest" in releases: https://github.com/Kamel-Media/Kamel/releases

And thanks for the fix! May not be the cleanest fix (runtime crash), but this should do for now.

**Comment by luca992** [comment]
@Skaldebane yeah not ideal. Sry haven't had time to port coils implementation.

It shouldn't crash, but rather not display anything and onError callback will get called.

I'll fix the release
