### ISSUE TITLE
null cannot be cast to non-null type android.graphics.Bitmap

### ISSUE THREAD

**Issue by TareHimself** [Kamel-Media/Kamel#48]
```
java.lang.NullPointerException: null cannot be cast to non-null type android.graphics.Bitmap
    at io.kamel.image.decoder.ImageBitmapDecoder.decode(AndroidImageBitmapDecoder.kt:21)
    at io.kamel.image.decoder.ImageBitmapDecoder$decode$1.invokeSuspend(Unknown Source:15)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

This is the image 
    
```
@file:Suppress("INLINE_FROM_HIGHER_PLATFORM")
package com.tarehimself.mangaz.ui.screens.search

import androidx.compose.foundation.Image
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Surface
import androidx.compose.material.Text
import androidx.compose.material.TextField
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.unit.dp
import com.tarehimself.mangaz.getPlatform
import io.kamel.core.Resource
import io.kamel.image.asyncPainterResource

@Composable
fun SearchResult(data: String) {
    Surface(
        modifier = Modifier.height(300.dp).border(
            width = 2.dp,
            color = Color.Transparent,
            shape = RoundedCornerShape(5.dp)
        ).padding(horizontal = 5.dp, vertical = 5.dp),
        color = Color.Transparent,
    ) {
        when (val resource = asyncPainterResource("https://www.example.com/image.jpg")) {
            is Resource.Loading -> {
                Text("Loading...")
            }
            is Resource.Success -> {
                val painter: Painter = resource.value
                Image(painter= painter, contentDescription = "Profile",modifier = Modifier.fillMaxSize())
            }
            is Resource.Failure -> {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = Color.Red,
                ){
                    TextField(value = resource.exception.stackTraceToString(), onValueChange = {})
                }
            }
        }
    }
}
```
And this is the config
```
@Composable
fun App(){
    val kamelConfig = KamelConfig {
        takeFrom(KamelConfig.Default)
    }

    CompositionLocalProvider(LocalKamelConfig provides kamelConfig) {
        Surface(
            modifier = Modifier.fillMaxSize(),
            color = MaterialTheme.colors.background,

            ) {
            SearchScreen()
        }
    }
}
```
The error is happening on android

**Comment by 7va** [comment]
Same issue with 0.9.0

**Comment by TareHimself** [comment]
Frankly I gave up and went with my own image loader , it's not all that complicated once you get into it

**Comment by TareHimself** [comment]
Oh , how did I not notice at the time . Thanks

**Comment by 7va** [comment]
Yeah, my bad too. Sorry and tnx!
