### ISSUE TITLE
File URLs should be handled as such on Desktop platform

### ISSUE THREAD

**Issue by eskatos** [Kamel-Media/Kamel#88]
Doing `asyncPainterResource("file://path/to/image.png")` currently fails with the following exception:

```
io.ktor.http.URLParserException: Fail to parse url: file://path/to/image.png
	at io.ktor.http.URLParserKt.takeFrom(URLParser.kt:21)
	at io.ktor.http.URLUtilsKt.URLBuilder(URLUtils.kt:25)
	at io.ktor.http.URLUtilsKt.Url(URLUtils.kt:13)
	at io.kamel.core.mapper.MappersKt$StringMapper$1.map(Mappers.kt:14)
	at io.kamel.core.mapper.MappersKt$StringMapper$1.map(Mappers.kt:8)
```

I would have expected this to load the local image from the filesystem.

I do this from a `commonMain` source set where I can't use `java.io.File`.

For the time being I worked around it with an `expect`/`actual` function to call `asyncPainterResource(File)` for `file:` URLs on the desktop platform. This is a totally viable workaround but supporting `file:` URLs out of the box would make Kamel easier to use.

**Comment by luca992** [comment]
that's java URI syntax right?

So the better way to do it would be either to write your own string mapper and use it in your KamelConfig:

https://github.com/Kamel-Media/Kamel/blob/86f216c1df9fafbe54ffb60ad3a11f5861ba5fb4/kamel-core/src/commonMain/kotlin/io/kamel/core/mapper/Mappers.kt#L8-L16

Or, either the default common string mapper split into expect actual definitions and extended to add uri support on jvm. Or is the java uri format useful on other targets as well? In that case the default common string mapper could be extended for other targets as well.

Lmk what you think

**Comment by eskatos** [comment]
The `file` URI scheme is not specific to the JVM https://datatracker.ietf.org/doc/html/rfc8089

Thanks for the much simpler workaround to use a URI instance.

**Comment by luca992** [comment]
Thanks for the reference.

`io.kamel.core.utils.URI` technically has the same constructor for all targets.. so I could add a way to create one in common if that is desired

**Comment by eskatos** [comment]
Using `asyncPainterResource(io.kamel.core.utils.URI("file://path/to/image.png"))` in my JVM `actual` doesn't load the image. I'll stick with my "dirty" workaround for now that basically does this on the JVM:

```kotlin
when {
    url.startsWith("file:") -> asyncPainterResource(Paths.get(URI.create(url)).toFile())
    else -> asyncPainterResource(url)
}
```

**Comment by luca992** [comment]
I just exposed the URI(str: String) constructor in common. And it's loading the example... 

<img width="1170" alt="Screenshot 2024-01-23 at 9 44 32 PM" src="https://github.com/Kamel-Media/Kamel/assets/4157455/32382fc2-0f07-422b-b2bf-f6abf613827c">

but also looks like it works with just a string too 🤔:

<img width="1330" alt="Screenshot 2024-01-23 at 9 47 08 PM" src="https://github.com/Kamel-Media/Kamel/assets/4157455/66149494-3d31-4b3d-9c90-a2b925087b70">

**Comment by eskatos** [comment]
Ha! :)

The path is right as I can load the image if I pass a `java.io.File` built from it.
I tried many variations but it doesn't work on Linux without my workaround! :thinking:

**Comment by luca992** [comment]
> Ha! :)
> 
> The path is right as I can load the image if I pass a `java.io.File` built from it. I tried many variations but it doesn't work on Linux without my workaround! 🤔

So it appears, `file://` is scoped to the jar's resources. That's why it is working for me.. But when I use an absolute path it does not

**Comment by eskatos** [comment]
Right, the image path I use is for a png file from the OS file system, outside the application resources.

**Comment by luca992** [comment]
Lol, I see now I was editing the ResourcesFetcher test... so obviously loading resources was working 😅

Anyways:
https://github.com/Kamel-Media/Kamel/pull/90

you can try it with: `0.10.0-SNAPSHOT` It should be working for local files with or without the "file://" prefix

**Comment by luca992** [comment]
@eskatos lmk if you get a chance to try it out

**Comment by eskatos** [comment]
I just tried and it fails by default parsing a `file:/path/to/image.png` URL which is what I get from other APIs.
If I manually change the URL to `file:///path/to/image/png` then it works out of the box.
It looks like KTor URL parser is not correct as this syntax is described in [Section 2 of the RFC](https://datatracker.ietf.org/doc/html/rfc8089#section-2) as shown in examples in the [Appendix B of the RFC](https://datatracker.ietf.org/doc/html/rfc8089#appendix-B).

I would understand you push this upstream to KTor at this point.

**Comment by luca992** [comment]
> I just tried and it fails by default parsing a `file:/path/to/image.png` URL which is what I get from other APIs.
> If I manually change the URL to `file:///path/to/image.png` then it works out of the box.
> It looks like KTor URL parser is not correct as this syntax is described in [Section 2 of the RFC](https://datatracker.ietf.org/doc/html/rfc8089#section-2) as shown in examples in the [Appendix B of the RFC](https://datatracker.ietf.org/doc/html/rfc8089#appendix-B).
> 
> I would understand you push this upstream to KTor at this point.
> 



If that's common I can add a case here:

(kamel-core/src/commonMain/kotlin/io/kamel/core/mapper/Mappers.kt)[kamel-core/src/commonMain/kotlin/io/kamel/core/mapper/Mappers.kt]

**Comment by eskatos** [comment]
Here's the KTOR issue https://youtrack.jetbrains.com/issue/KTOR-6709

**Comment by luca992** [comment]
@eskatos I re-published with support for `file:/` and `file:/` in [kamel-core/src/commonMain/kotlin/io/kamel/core/mapper/Mappers.kt](https://github.com/Kamel-Media/Kamel/blob/fileUrlFetcher/kamel-core%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fkamel%2Fcore%2Fmapper%2FMappers.kt)

I got rid of assuming a `/` prefix is a file because that would break things when using a defaultRequest with a base url.

**Comment by eskatos** [comment]
Sorry it took me so long to get back to you.
All good with you latest publication, thank you very much :heart:

**Comment by luca992** [comment]
@eskatos it should be in the 1.0 beta. The only reason it's beta is because it uses ktor `3.0` beta still. I'm waiting on a release.
